#!/usr/bin/env python3
"""Migrate all data + users/permissions from InfluxDB into QuestDB.

Reads a v1 or v2 InfluxDB server, writes the time series into QuestDB over ILP
using the ``<db>_<measurement>`` table-naming convention the fork's InfluxQL
/query endpoint expects, and emits machine-readable artifacts so the ACL is
produced consistently with the data that was actually written:

  - migration-manifest.json : [{influx_db, prefix, tables[]}] -- the operator's
    Grafana ?db= mapping and the input the ACL generator consumes.
  - principals.json         : [{name, is_admin, grants[]}] -- InfluxDB users and
    permissions, for replay into conf/acl.conf.

Producing conf/acl.conf directly is OPT-IN (``--emit-acl-conf``): by default the
canonical acl.conf is generated by the ACL tool from the artifacts above, so
there is a single acl.conf writer.

db/bucket names that are not already clean ``[A-Za-z0-9_]`` identifiers are
REJECTED (non-zero exit): the /query prefix is literal ``db + "_"``, so a name
must be renamed upstream rather than silently sanitized.

Run ``--dry-run`` first to see planned tables, row counts and the artifacts
without writing anything.

Examples
--------
  # v1 source, dry run
  influx_migrate.py --source-type v1 --influx-url http://localhost:8086 \\
      --influx-user admin --influx-password secret \\
      --questdb-ilp 'http::addr=localhost:9000;' --dry-run

  # v2 source, real run, also emit acl.conf directly
  influx_migrate.py --source-type v2 --influx-url http://localhost:8086 \\
      --influx-token "$INFLUX_TOKEN" --influx-org my-org \\
      --questdb-ilp 'http::addr=localhost:9000;' \\
      --emit-acl-conf --acl-out conf/acl.conf --credentials-out credentials.csv
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from typing import Dict, List, Optional

from acl import AclNameCollision, build_entries, render, render_credentials_csv
from model import (
    InvalidScopeName,
    MigrationStats,
    Principal,
    scope_prefix,
    table_name,
    validate_scope,
)
from readers.base import InfluxReader
from writer import QuestDBWriter

log = logging.getLogger("influx_migrate")


def main(argv: Optional[List[str]] = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    source_type = _resolve_source_type(args)
    reader = _build_reader(source_type, args)
    use_prefix = not args.no_prefix

    try:
        scopes = _select(reader.scopes(), args.databases or args.buckets)
        if not scopes:
            log.error("no databases/buckets to migrate; nothing to do")
            return 1

        if use_prefix and not _validate_scopes(scopes):
            return 2  # hard-fail: an invalid db/bucket name was found

        if not _idempotency_preflight(reader, scopes, args, use_prefix):
            return 3  # target tables already hold data; re-run would duplicate

        log.info("scopes to migrate: %s", ", ".join(scopes))
        manifest = _migrate_data(reader, scopes, args, use_prefix)
        _write_manifest(manifest, args)
        _export_principals(reader, args)
        return 0
    finally:
        reader.close()


def _validate_scopes(scopes: List[str]) -> bool:
    """Reject any db/bucket name that is not a clean identifier.

    Returns True if all names are clean. Logs every offender so the operator can
    rename them upstream in one pass.
    """
    bad: List[str] = []
    for scope in scopes:
        try:
            validate_scope(scope)
        except InvalidScopeName:
            bad.append(scope)
    for name in bad:
        log.error(
            "db/bucket %r is not a clean [A-Za-z0-9_] identifier; rename it "
            "upstream (the QuestDB table prefix is a literal '<db>_'). Aborting.",
            name,
        )
    return not bad


def _idempotency_preflight(
    reader: InfluxReader, scopes: List[str], args, use_prefix: bool
) -> bool:
    """Refuse to run if any target table already holds data.

    ILP ingestion appends, so a second run duplicates rows. Returns True (proceed)
    when nothing is at risk; False (abort) when a non-empty target table exists
    and --allow-duplicate-rows was not given. Skipped for --dry-run, when the
    user opted into duplicates, or when the QuestDB target is reached over a
    non-HTTP transport (no query endpoint to check against -- warned, not fatal).
    """
    if args.dry_run or args.allow_duplicate_rows:
        return True
    base = _http_base_from_ilp(args.questdb_ilp)
    if base is None:
        log.warning(
            "cannot check for existing rows over a non-HTTP ILP transport; "
            "re-running appends and may duplicate data (use --allow-duplicate-rows "
            "to silence this)"
        )
        return True
    auth = _ilp_auth_header(args.questdb_ilp)
    non_empty: List[str] = []
    for scope in scopes:
        for measurement in _select(reader.measurements(scope), args.measurements):
            table = table_name(args.table_name_template, scope, measurement, use_prefix)
            if _table_row_count(base, table, auth) > 0:
                non_empty.append(table)
    if non_empty:
        log.error(
            "target tables already contain data: %s. ILP appends, so re-running "
            "would DUPLICATE rows. Drop/dedup them, or pass --allow-duplicate-rows "
            "to proceed anyway. Aborting.",
            ", ".join(sorted(set(non_empty))),
        )
        return False
    return True


def _http_base_from_ilp(conf: str) -> Optional[str]:
    """Derive an http(s)://host:port base from a questdb ILP conf string.

    Returns None for tcp transports (no HTTP query endpoint available)."""
    import re

    proto = conf.split("::", 1)[0].strip().lower() if "::" in conf else ""
    if proto not in ("http", "https"):
        return None
    m = re.search(r"addr=([^;]+)", conf)
    if not m:
        return None
    return f"{'https' if proto == 'https' else 'http'}://{m.group(1).strip()}"


def _ilp_auth_header(conf: str) -> Optional[str]:
    """Build an HTTP Authorization header from the ILP conf, if it carries auth.

    Supports HTTP basic (``username``/``password``) and token (``token``) auth so
    the pre-flight count query can read tables on an ACL-protected target."""
    import base64
    import re

    tok = re.search(r"(?:^|;)token=([^;]+)", conf)
    if tok:
        return "Bearer " + tok.group(1).strip()
    user = re.search(r"(?:^|;)username=([^;]+)", conf)
    pwd = re.search(r"(?:^|;)password=([^;]+)", conf)
    if user and pwd:
        raw = f"{user.group(1).strip()}:{pwd.group(1).strip()}".encode("utf-8")
        return "Basic " + base64.b64encode(raw).decode("ascii")
    return None


def _table_row_count(base: str, table: str, auth: Optional[str] = None) -> int:
    """Return the row count of a QuestDB table, or 0 if it does not exist."""
    import urllib.parse
    import urllib.request

    # Quote the table name as a SQL string literal (single quotes) for FROM.
    q = "SELECT count() FROM '" + table.replace("'", "''") + "'"
    url = base.rstrip("/") + "/exec?" + urllib.parse.urlencode({"query": q})
    req = urllib.request.Request(url)
    if auth:
        req.add_header("Authorization", auth)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            payload = json.loads(resp.read().decode("utf-8", "replace"))
    except Exception:  # noqa: BLE001 - table absent returns 4xx; treat as empty
        return 0
    dataset = payload.get("dataset") or []
    if dataset and dataset[0]:
        try:
            return int(dataset[0][0])
        except (TypeError, ValueError):
            return 0
    return 0


def _migrate_data(
    reader: InfluxReader, scopes: List[str], args, use_prefix: bool
) -> List[dict]:
    writer = QuestDBWriter(args.questdb_ilp, dry_run=args.dry_run, batch_size=args.batch_size)
    manifest: List[dict] = []
    planned: Dict[str, str] = {}
    try:
        for scope in scopes:
            measurements = _select(reader.measurements(scope), args.measurements)
            tables: List[str] = []
            for measurement in measurements:
                schema = reader.schema(scope, measurement)
                resolved = table_name(
                    args.table_name_template, scope, measurement, use_prefix
                )
                tables.append(resolved)
                planned[f"{scope}.{measurement}"] = resolved
                log.info("migrating %s.%s -> table %s", scope, measurement, resolved)
                for row in reader.rows(scope, measurement, schema):
                    row.table = resolved
                    writer.write(row, schema)
                writer.flush()
            manifest.append(
                {
                    "influx_db": scope,
                    "prefixed": use_prefix,
                    "prefix": scope_prefix(scope) if use_prefix else "",
                    "tables": tables,
                }
            )
    finally:
        writer.close()

    _report(writer.stats(), planned, args.dry_run)
    return manifest


def _write_manifest(manifest: List[dict], args) -> None:
    if not args.manifest_out:
        return
    text = json.dumps(manifest, indent=2, sort_keys=True)
    if args.dry_run:
        log.info("[dry-run] manifest that would be written to %s:\n%s", args.manifest_out, text)
        return
    with open(args.manifest_out, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    log.info("wrote migration manifest (%d scopes) to %s", len(manifest), args.manifest_out)


def _export_principals(reader: InfluxReader, args) -> None:
    principals: List[Principal] = reader.principals()
    payload = [
        {
            "name": p.name,
            "is_admin": p.is_admin,
            "grants": [{"scope": g.scope, "access": g.access.value} for g in p.grants],
        }
        for p in principals
    ]

    if args.principals_out:
        text = json.dumps(payload, indent=2, sort_keys=True)
        if args.dry_run:
            log.info(
                "[dry-run] principals that would be written to %s:\n%s",
                args.principals_out,
                text,
            )
        else:
            with open(args.principals_out, "w", encoding="utf-8") as fh:
                fh.write(text + "\n")
            log.info("wrote %d principals to %s", len(payload), args.principals_out)

    if args.emit_acl_conf:
        _emit_acl_conf(principals, args)


def _emit_acl_conf(principals: List[Principal], args) -> None:
    """Optional: produce conf/acl.conf directly (off by default).

    The canonical acl.conf is normally generated by the ACL tool from
    principals.json + migration-manifest.json so there is a single writer; this
    path exists for standalone use.
    """
    if not principals:
        log.info("no principals found; not writing acl.conf")
        return
    password_map = _load_password_map(args.password_map)
    try:
        entries = build_entries(
            principals,
            args.multi_scope_policy,
            password_map,
            use_prefix=not args.no_prefix,
        )
    except AclNameCollision as exc:
        raise SystemExit(f"acl.conf generation failed: {exc}") from exc
    if not entries:
        log.warning("no acl.conf entries produced (all skipped)")
        return

    acl_text = render(entries)
    if args.dry_run:
        log.info("[dry-run] acl.conf that would be written to %s:\n%s", args.acl_out, acl_text)
    else:
        with open(args.acl_out, "w", encoding="utf-8") as fh:
            fh.write(acl_text)
        log.info("wrote %d ACL entries to %s", len(entries), args.acl_out)

    if args.credentials_out:
        csv_text = render_credentials_csv(entries)
        if args.dry_run:
            log.info("[dry-run] credentials CSV that would be written to %s", args.credentials_out)
        else:
            with open(args.credentials_out, "w", encoding="utf-8") as fh:
                fh.write(csv_text)
            log.info("wrote credentials for %d users to %s", len(entries), args.credentials_out)


def _report(stats: Dict[str, MigrationStats], planned: Dict[str, str], dry_run: bool) -> None:
    prefix = "[dry-run] would migrate" if dry_run else "migrated"
    total = 0
    for table, st in sorted(stats.items()):
        total += st.rows
        extra = ""
        if st.fields_skipped_null or st.tags_skipped_empty:
            extra = f" (skipped {st.fields_skipped_null} null fields, {st.tags_skipped_empty} empty tags)"
        log.info("%s %d rows -> %s%s", prefix, st.rows, table, extra)
    for key, resolved in sorted(planned.items()):
        if resolved not in stats:
            log.info("%s 0 rows -> %s (empty measurement %s)", prefix, resolved, key)
    log.info("%s %d rows across %d tables", prefix, total, len(planned))


def _build_reader(source_type: str, args) -> InfluxReader:
    if source_type == "v1":
        from readers.v1 import V1Reader

        return V1Reader(
            url=args.influx_url,
            username=args.influx_user,
            password=args.influx_password,
            page_size=args.page_size,
        )
    from readers.v2 import V2Reader

    if not args.influx_token or not args.influx_org:
        raise SystemExit("v2 source requires --influx-token and --influx-org")
    from datetime import timedelta

    return V2Reader(
        url=args.influx_url,
        token=args.influx_token,
        org=args.influx_org,
        window=timedelta(minutes=args.v2_window_minutes),
    )


def _resolve_source_type(args) -> str:
    if args.source_type != "auto":
        return args.source_type
    # Auto-detect: v2 answers /health with a JSON identifying influxdb; v1 does
    # not. Probe cheaply with urllib so neither client lib is needed yet.
    import urllib.request

    base = args.influx_url.rstrip("/")
    try:
        with urllib.request.urlopen(f"{base}/health", timeout=10) as resp:
            body = resp.read(200).decode("utf-8", "replace")
            if '"name"' in body or "influxdb" in body.lower():
                log.info("auto-detected InfluxDB v2 (/health responded)")
                return "v2"
    except Exception:  # noqa: BLE001
        pass
    log.info("auto-detected InfluxDB v1 (defaulting; /health did not identify v2)")
    return "v1"


def _select(available: List[str], wanted: Optional[List[str]]) -> List[str]:
    if not wanted:
        return list(available)
    wanted_set = set(wanted)
    selected = [a for a in available if a in wanted_set]
    for m in sorted(wanted_set - set(available)):
        log.warning("requested %r not found in source; ignoring", m)
    return selected


def _load_password_map(path: Optional[str]) -> Dict[str, str]:
    if not path:
        return {}
    mapping: Dict[str, str] = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "," not in line:
                log.warning("ignoring malformed password-map line: %r", line)
                continue
            name, password = line.split(",", 1)
            mapping[name.strip()] = password.strip()
    return mapping


def _csv_list(value: str) -> List[str]:
    return [v.strip() for v in value.split(",") if v.strip()]


def _parse_args(argv: Optional[List[str]]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="influx_migrate.py",
        description="Migrate data + users/permissions from InfluxDB to QuestDB.",
    )
    src = p.add_argument_group("source (InfluxDB)")
    src.add_argument("--source-type", choices=["v1", "v2", "auto"], default="auto")
    src.add_argument("--influx-url", required=True, help="e.g. http://localhost:8086")
    src.add_argument("--influx-user", default="", help="v1 username")
    src.add_argument("--influx-password", default="", help="v1 password")
    src.add_argument("--influx-token", default="", help="v2 API token")
    src.add_argument("--influx-org", default="", help="v2 organization")
    src.add_argument(
        "--page-size",
        type=int,
        default=50_000,
        help="v1 read pagination: rows per SELECT page (bounds reader memory)",
    )
    src.add_argument(
        "--v2-window-minutes",
        type=int,
        default=60,
        help="v2 read time-window size in minutes (bounds per-query work; a "
        "single unbounded query times out on large buckets -- lower this for "
        "very dense data)",
    )

    tgt = p.add_argument_group("target (QuestDB)")
    tgt.add_argument(
        "--questdb-ilp",
        required=True,
        help="questdb client conf string, e.g. 'http::addr=localhost:9000;'",
    )
    tgt.add_argument(
        "--batch-size",
        type=int,
        default=0,
        help="ILP auto_flush_rows: flush a batch every N rows (0 = client default)",
    )
    tgt.add_argument(
        "--allow-duplicate-rows",
        action="store_true",
        help="skip the pre-flight check that refuses to write into a non-empty "
        "target table (ILP appends, so re-running otherwise duplicates rows)",
    )

    sel = p.add_argument_group("selection")
    sel.add_argument("--databases", type=_csv_list, help="v1 db allowlist (comma-separated)")
    sel.add_argument("--buckets", type=_csv_list, help="v2 bucket allowlist (comma-separated)")
    sel.add_argument("--measurements", type=_csv_list, help="measurement allowlist")

    name = p.add_argument_group("naming")
    name.add_argument(
        "--table-name-template",
        default="{db}_{measurement}",
        help="single underscore separator required by the /query endpoint",
    )
    name.add_argument(
        "--no-prefix",
        action="store_true",
        help="single-DB setups: use bare measurement names (no <db>_ prefix)",
    )

    art = p.add_argument_group("artifacts")
    art.add_argument(
        "--manifest-out",
        default="migration-manifest.json",
        help="write the influx_db->prefix->tables manifest here (the ACL input)",
    )
    art.add_argument(
        "--principals-out",
        default="principals.json",
        help="write InfluxDB users/grants here for ACL generation",
    )

    acl = p.add_argument_group("acl (opt-in; canonical acl.conf is built by the ACL tool)")
    acl.add_argument(
        "--emit-acl-conf",
        action="store_true",
        help="also produce conf/acl.conf directly from this tool",
    )
    acl.add_argument("--acl-out", default="conf/acl.conf", help="acl.conf path when --emit-acl-conf")
    acl.add_argument("--password-map", help="CSV name,password to reuse known passwords")
    acl.add_argument("--credentials-out", help="write generated username,password CSV here")
    acl.add_argument(
        "--multi-scope-policy",
        choices=["widest", "skip", "split-note"],
        default="widest",
        help="how to map a user with grants on multiple databases",
    )

    ops = p.add_argument_group("ops")
    ops.add_argument("--dry-run", action="store_true", help="read + report, write nothing")
    ops.add_argument("--verbose", action="store_true")
    return p.parse_args(argv)


if __name__ == "__main__":
    sys.exit(main())
